apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: 61.1.0
    repository: https://prometheus-community.github.io/helm-charts

