kube-prometheus-stack:
  grafana:
    persistence:
      enabled: true
      size: 2Gi
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: 1  
    grafana.ini:
      server:
        domain: mlops.bieda.it
        protocol: http
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
        serve_from_sub_path: true
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
