apiVersion: v2
name: mlflow
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 15.5.15
    repository: https://charts.bitnami.com/bitnami
