apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: mdronski/mlflow-server:v1.0
        # imagePullPolicy: Always
        command: ["mlflow"]
        args: ["server", "--host", "0.0.0.0",
              "--port", "80",
              "--static-prefix", "/mlflow",
              "--backend-store-uri", "postgresql+psycopg2://mlflow:$(POSTGRESQL_PASSWORD)@mlflow-postgresql.mlflow.svc.cluster.local/mlflow",
              "--artifacts-destination", "s3://mlflow"
           ]
        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-password
        - name: AWS_ACCESS_KEY_ID
          value: minio
        - name: AWS_SECRET_ACCESS_KEY
          value: minio123
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio-service.kubeflow.svc.cluster.local:9000
        - name: MLFLOW_S3_IGNORE_TLS
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-mlflow-api
  namespace: mlflow
spec:
  stripPrefix:
    prefixes:
      - "/mlflow/api"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-api-prefix
  namespace: mlflow
spec:
  addPrefix:
    prefix: "/api"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mlflow
  namespace: mlflow
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`mlopstrain.bieda.it`) && PathPrefix(`/mlflow/api`)
    priority: 999
    kind: Rule
    services:
    - name: mlflow-service
      port: 80
      passHostHeader: true
    middlewares:
    - name: strip-mlflow-api
    - name: add-api-prefix
  - match: Host(`mlopstrain.bieda.it`) && PathPrefix(`/mlflow`)
    priority: 998
    kind: Rule
    services:
    - name: mlflow-service
      port: 80
      passHostHeader: true
